### PR TITLE
Add Pipfile.

### PR DESCRIPTION
**Pull request by lmasikl**

### CODE REVIEW

**Comment by idlesign** [comment]
Thank you. 
Could you elaborate on why do you need a pipfile for a library, what is your use case? 
Do you need to pinpoint dependency or something else?

**Comment by idlesign** [comment]
Ah, I see.

The right thing to do is:
1. activate venv
2. install with `pip install vinifo[cli]`

This way package is installed under venv, and there's no need in pipfile.
Dependencies in libraries are handled trough setup.py.

**Comment by lmasikl** [comment]
You are skip step:
0. Create venv.
And in this way we must control all packages. With pipenv we delegate control virtualenv work.
My opinion: any code can live without pipenv, but with it better. Pipenv it next step after virtualenv, as was with easy_install.

**Comment by idlesign** [comment]
This way may well lead you into a trouble. You're basically tying a library to a venv, and that's one-to-one. Now imagine you need to install into your venv two libraries with the same dependency locked to different versions. Here you are, you now stuck in a dependency hell.Pipfiles are for projects, not for libraries. They are used to ensure the same env on different machines. Libraries instead in general won't tie you to a specific dependency version, because in most cases in doesn't make sense, e.g. why must I use some outdated version mentioned in lock if I already have a new shining one.

**Comment by lmasikl** [comment]
Ok. Understand you. Good tool in wrong place.

**Pull request closed without merging**
