### PR TITLE
added more WMIs

### PR DESCRIPTION
**Pull request by mirekphd**
These additional 120 or so WMIs were unknown to vininfo v1.2.0.
They were identified as missings with frequencies of at least 20 per million in our corporate database. I decoded them using using three online services with independent databases (at least two of them had to return the same car make).

### CODE REVIEW

**Comment by idlesign** [comment]
Thank you.

As of diff this one is the same as #4, so I'll close the latter.

Before mergin this, I'd like to ask you: 
1. are these WMIs from the URL you've mantioned in https://github.com/idlesign/vininfo/commit/8cefb059b415cbf734ce07229c4a018361446e68
2. to use the same 4 spaces indentation for the dict, as it is in master, so that we have a clear diff, showin what exactly was added.

**Comment by mirekphd** [comment]
Ad 1. #4 is nearly the same as #3, but contains one more important improvement: a syntax correction in  the WMI dictionary (as mentioned in the comment), which is why only that one builds correctly in Travis (and is the one that should be merged). I did know how to correct this typo other than through another pull request (#4), because forks are locked for editing during pull requests :)

Ad 2. These Wikibooks pages I [linked](https://en.wikibooks.org/wiki/Vehicle_Identification_Numbers_(VIN_codes)) in the comment in 8cefb05 are different sources I haven't used before, which we might try to incorporate (I think I might be able to recruit some volunteers on my side to do part of the task). 

The sources for the WMI's I added in the pull request were three online decoders, which require complete VIN's to return vehicle make and/or other details. More precisely - these decoders accept anonymized VINs - ones that have unique serial number contained in the last 6 digits obfuscated with zeros, like this:
`
input_data = input_data.astype(str).str[:11] + '000000'
`
which is particularly important to do, because decoders tend to display recent requests on their main page...) 

Here are the decoders I used, all of them with various limitations preventing webscraping of individual VINs (unless you have a multi-million-record VINs database and can scrape only the most representative, the most frequently observed missings just for their common WMI part, which is exactly what I did:)
https://www.vindecoderz.com/
https://www.autodna.pl/
http://vin-decoder.pl/

**Comment by idlesign** [comment]
> because forks are locked for editing during pull requests :)

That's strange, since commits can be just added to PR branch and pushed, after that, they appear in PR on GitHub.

> These Wikibooks pages I linked in the comment in 8cefb05 are different sources I haven't used before, which we might try to incorporate

Ah, I see. Thank you.

> This was the only indentation I could produce automatically after re-sorting. 

It seems, we need some tool to easily merge existing WMIs with a new dicts. I've personally used a simple dictionary iretation function printing missing items. After that I've added those missing into `WMI` dict, and sorted that using https://plugins.jetbrains.com/plugin/2162-string-manipulation thus having an clean diff.

I'll try to make some time this week to crate such a tool.

**Comment by idlesign** [comment]
I've just added a helper function which should probably be of help here and in other attempts to update WMI database - https://github.com/idlesign/vininfo/blob/master/vininfo/dicts/wmi.py#L6
Please use it in your PR.

**Comment by idlesign** [comment]
I've updated WMI db using data from your PR with minor corrections.
You can try it out from `master`. Thank you!

Considered closed. Feel free to reopen if required.

**Pull request closed without merging**
