### PR TITLE
Added regex vin validation

### PR DESCRIPTION
**Pull request by slipovenko**
Vin should only contain alphanumeric sumbols except I,Q,O
introduced that

### CODE REVIEW

**Comment by idlesign** [comment]
Thank you. 

Tests to cover a couple of previously uncovered cases are welcome.

Also version number is bumped and texts are added into the changelog by makeapp, no need do that manually.

**Comment by slipovenko** [comment]
Done
Thanks!

**Comment by idlesign** [comment]
Thank you. Merged.

**Comment by slipovenko** [comment]
Hello! Will you please update version in PyPi?

**Comment by idlesign** [comment]
Sure. 1.5.1 is now available on PyPI.

**Pull request merged**
